### ISSUE TITLE
No matching distribution found for Telethon~=1.26.1

### ISSUE THREAD

**Issue by Cyrilnkl** [un1cum/Beast_Bomber#64]
Hey, I have this error when installing and I don't know how to fix it : 

<img width="1272" alt="Capture d’écran 2023-02-08 à 11 17 29" src="https://user-images.githubusercontent.com/65498535/217501590-11b68bc7-d3f0-4775-8a76-bbf3adf20cf0.png">

**Comment by un1cum** [comment]
`Try installing telethon like this:`
```
pip3 install telethon
```
![image](https://user-images.githubusercontent.com/80776324/217512565-7f0cce90-1a44-4db2-a339-5b3263d8457b.png)
`If that doesn't work, upgrade pip:`
```
python -m pip install --upgrade pip
```
If that doesn't help either, try reinstalling **Python.**
