### ISSUE TITLE
at this point it finally ran with a virtual env

### ISSUE THREAD

**Issue by myk-coder** [un1cum/Beast_Bomber#67]
what i am doing wrong?

![image](https://user-images.githubusercontent.com/103906906/218086492-05489b76-5b93-4eda-bb50-63d6f4e2ea73.png)

**Comment by un1cum** [comment]
If this error occurs, it means that telegram is blocking messages from your account(s). You just need to wait until telegram allows you to send messages again, or simply use another account(s). If you get this error even when using other accounts, it means that telegram has blocked messages from your IP, in which case all you have to do is wait. I also advise you to check if all the dependencies are installed correctly.

**Comment by myk-coder** [comment]
But is there a way I can use my proxies on the bot?

**Comment by un1cum** [comment]
At the moment beast bomber has no possibility to use a proxy for telegram spam, I am going to add this soon.

**Comment by myk-coder** [comment]
hey i got from proxy seller, how do i make use of proxy on mobile, any idea how

**Comment by myk-coder** [comment]
hello, do you know anywhere i can purchase live smtps
