### ISSUE TITLE
No emails arrived to inbox !

### ISSUE THREAD

**Issue by darkhacknet** [un1cum/Beast_Bomber#69]
Hello, 

I have successfully ran the script and everythins seems to be good while trying to spam mail using the 2nd option but the scrip finishes the spam normally but there are no emails on into the gmail inbox, so something is wrong. 

Are you aware of this ? Would you be so kind to help me to solve it ? 

Thanks in advance. 
Regards.

**Comment by un1cum** [comment]
Hello. Check if you have done everything according to the instructions and check the quality of email accounts that you put in the **input\email_accounts.txt** file, often services like **Google** or **Yahoo** just block them and mark them as spam account. I will also say that for spam to work, you need a special password that gives access to the applications. You can read more on the website of the email service you use. That's all I can do to help.
