### ISSUE TITLE
DDos not working.

### ISSUE THREAD

**Issue by VenomousXD** [un1cum/Beast_Bomber#71]
I'm trying it in 40 threads 60 seconds but it doesn't do anything. proxies.txt is empty. Do I have to add the proxies myself? If so, in which format?

**Comment by un1cum** [comment]
A DDoS attack from one pc has practically **no effect**. For this function to work correctly, you need a proxies in the **following format:** ip:port or username:pas@ip:port

**Before writing that something is not working and asking questions in the issues, please, read the instructions given in the repository and find the information on the Internet (often the answers are already given there)**.
