### ISSUE TITLE
is there a reason for delete permission denied ?

### ISSUE THREAD

**Issue by DeadEyeSamurai** [un1cum/Beast_Bomber#72]
when trying to delete Beast_Bomber folder it denies permission any particular reason?

**Comment by un1cum** [comment]
Hi. If you can't remove a folder, then most likely some program is using it, try restarting your PC and try deleting it again. Otherwise, you have some problems in your os, try to find the answer to your question on the internet.

**Comment by DeadEyeSamurai** [comment]
Hey thanks for the reply i think you were right and it was just a glitch in the os because every file was throwing up the same error, sorted it by chmod 777 (Your pathway opt) then rm (your pathway opt again)
