### ISSUE TITLE
no module named fade

### ISSUE THREAD

**Issue by x9o** [un1cum/Beast_Bomber#81]
i already did pip install fade and it says its installed but i still cant run it

**Comment by xpghard** [comment]
@x9o can you show any screenshot?

**Comment by un1cum** [comment]
If you still get an error saying that the **fade** module is not installed, this probably means that you have **multiple versions** of pip.

You can try 
```
pip3 install fade
``` 
and then run: 
```
python3 beast.py
```

If that doesn't work, I suggest reinstalling python and pip
