### ISSUE TITLE
ModuleNotFoundError: No module named 'core.sms_spam'

### ISSUE THREAD

**Issue by terosque** [un1cum/Beast_Bomber#95]
# python beast.py
Traceback (most recent call last):
  File "/home/kali/Beast_Bomber/beast.py", line 20, in <module>
    from core.sms_spam.sms import SMSAttack
ModuleNotFoundError: No module named 'core.sms_spam'

Can you help please ?

**Comment by un1cum** [comment]
This error may be related to the version of Python, try reinstalling it. If that doesn't help, use the version on replit or telegram:

https://replit.com/@un1cum/Beast-Bomber
https://t.me/idfhgsdwaefwe_caramel_bot

I can't help you with anything else.
