### ISSUE TITLE
Getting this ERROR

### ISSUE THREAD

**Issue by khansaad1275** [un1cum/Beast_Bomber#99]
![image](https://github.com/un1cum/Beast_Bomber/assets/32749921/fd190626-91d5-443f-92df-fde4e6b81fac)

**Comment by un1cum** [comment]
The error says that the `fake_usera` package does not exist. In your case, you need to enter this command:
```
pip install fake-useragent
```

**If you had followed the** [installation instructions](https://github.com/un1cum/Beast_Bomber/tree/main#-manual)**, you would not have gotten this error.**

**You need to learn how to read elementary pip errors like this one.**
